# Generated by Django 2.2.6 on 2019-10-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191024_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='not started', max_length=120)),
                ('priority', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Product')),
            ],
        ),
    ]
