# Generated by Django 2.2.6 on 2019-11-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='storyPoints',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
