# Generated by Django 2.2.7 on 2019-11-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pbi_storypoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbiTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('storyPoints', models.IntegerField(default=0, null=True)),
                ('Pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Pbi')),
                ('assigined_team_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TeamMember')),
            ],
        ),
    ]
