# Generated by Django 2.2.7 on 2019-11-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_pbitasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbitasks',
            name='assigined_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TeamMember'),
        ),
        migrations.AlterField(
            model_name='pbitasks',
            name='storyPoints',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
