# Generated by Django 2.2.7 on 2019-11-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191106_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
