# Generated by Django 2.2.7 on 2019-11-17 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_pbi_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbitasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(default='Not Started', max_length=120),
        ),
        migrations.AlterField(
            model_name='pbitasks',
            name='assigined_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pbitasks',
            name='status',
            field=models.CharField(default='Not Started', max_length=120),
        ),
        migrations.AlterField(
            model_name='pbitasks',
            name='storyPoints',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
