# Generated by Django 2.2.7 on 2019-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20191124_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='team_member',
        ),
        migrations.AddField(
            model_name='teammember',
            name='product',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
