# Generated by Django 2.2.7 on 2019-11-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20191125_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Product'),
        ),
    ]
