# Generated by Django 2.2.7 on 2019-11-25 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20191125_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbitasks',
            name='assigined_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
