# Generated by Django 2.2.7 on 2019-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20191125_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='completedSprint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='ongoingSprint',
            field=models.IntegerField(default=1),
        ),
    ]
