# Generated by Django 2.2.7 on 2019-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20191126_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sprintCapacity',
            field=models.IntegerField(default=100),
        ),
    ]
