# Generated by Django 2.2.7 on 2019-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_product_sprintcapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='completedSprint',
            field=models.IntegerField(default=-1),
        ),
    ]
