from django.urls import path
from .views import *

urlpatterns = [
    path('showProjects/', showProjects),
    path('createProject/', createProject),
    path('deleteProject/', deleteProject),
    path('saveProjectDescription/', updateProjectDescription),
    path('getPBIs/', showPBIs),
    path('createPBI/', createPBI),
    path('deletePBI/', deletePBI),
    path('editPBI/', editPBI),
    path('priorityUp/', priorityUp),
    path('priorityDown/', priorityDown),
    path('editPBITask/', editPBITask),
    path('createPBITask/', createPBITask),
    path('getPBITasks/', showPBITasks),
    path('sendEmail/', sendEmail),
    path('validateEmail/<str:user_id>/<str:product_title>/<str:token>', validateEmail),
    path('inviteDeveloper/', inviteDeveloper),
    path('inviteScrumMaster/', inviteScrumMaster),
    path('getStats/', getStats),
    path('getOtherStats/', getOtherStats),
    path('changePBITaskStatus/', ChangePBITaskEffort),
    path('deletePBITask/', deletePBITask),
    path('addPBItoSprint/', addPBItoSprint),
    path('removePBIfromSprint/', removePBIfromSprint),
    path('getUserID/', getUserID),
    path('getProductOwnerName/', getProductOwnerName),
    path('isProductOwner/', isProductOwner),
    path('isScrumMaster/', isScrumMaster),
    path('isDeveloper/', isDeveloper),
    path('PBITask/Developers/', getTeamDevelopers),
    path('endSprint/', endSprint),
    path('sprintload/', sprintLoad),
    path('cumefforthours/', cumEffortHours),
    path('delPBIs/', delSprintPBI),
    path('getVelocityStats/', getVelocityStats),
]